swagger: '2.0'
info:
  title: CMYKhub Reseller API
  version: '1.0'
  contact:
    name: Michael Denholm
    email: michael.denholm@cmykhub.com
    url: http://www.cmykhub.com
  description: Quoting and Ordering interface for Resellers
schemes:
  - https
consumes:
  - application/json
  - application/octet-stream
  - application/json-patch+json
produces:
  - application/json
  - application/octet-stream
security:
  - API Key: []
paths:
  /:
    get:
      operationId: getDiscovery
      summary: Returns a discovery resource
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Discovery Resource
        401:
          $ref: "#/responses/Unauthorized"
  /man/customers:
    get:
      operationId: getCustomers
      summary: Returns all customers
      description: Returns all customers
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: customerId
          required: false
          type: string
          allowEmptyValue: false
          description: The customer id
        - in: query
          name: resellerId
          required: false
          type: string
          allowEmptyValue: false
          description: The reseller id
        - in: query
          name: page
          required: false
          type: integer
          allowEmptyValue: false
          description: The index of the paged results
        - in: query
          name: size
          required: false
          type: integer
          allowEmptyValue: false
          description: The size of the paged results
        - in: query
          name: sort
          required: false
          type: string
          allowEmptyValue: false
          description: The field being used to sort the results
        - in: query
          name: asc
          required: false
          type: boolean
          allowEmptyValue: false
          description: The sort direction
      responses:
        200:
          description: Products Resource
          schema:
            type: object
        401:
          $ref: "#/responses/Unauthorized"
  /man/customers/{id}:
    get: 
      operationId: getCustomerById
      summary: Returns customer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the customer
          type: string
      responses:
        200:
          description: Customer Resource
        400:
          description: Invalid id
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /man/products:
    get:
      operationId: getProducts
      summary: Returns all products
      description: Returns all products
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          required: false
          type: string
          allowEmptyValue: false
          description: Filters products by name
      responses:
        200:
          description: Products Resource
          schema:
            type: object
        401:
          $ref: "#/responses/Unauthorized"
  /man/wideformat/products:
    get:
      operationId: getWideFormatProducts
      summary: Returns all wide format products
      description: Returns all wide format products
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          required: false
          type: string
          allowEmptyValue: false
          description: Filters products by name
      responses:
        200:
          description: Wide Format Products Resource
          schema:
            type: object
        401:
          $ref: "#/responses/Unauthorized"
  /man/papers:
    get:
      operationId: getPapers
      summary: Returns papers optionally filtered by name
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          required: false
          type: string
          allowEmptyValue: false
          description: Filters papers by name
        - in: query
          name: paperId
          required: false
          type: string
          allowEmptyValue: false
          description: Returns the paper for the specified id
      responses:
        200:
          description: Papers Resource
          schema:
            type: object
        401:
          $ref: "#/responses/Unauthorized"
  /man/papers/{id}:
    get: 
      operationId: getPapersById
      summary: Returns paper
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the paper
          type: string
      responses:
        200:
          description: Paper Resource
        400:
          description: Invalid id
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /man/finishings:
    get:
      operationId: getFinishings
      summary: Returns finishings optionally filtered by name
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          required: false
          type: string
          allowEmptyValue: false
          description: Filters finishings by name
        - in: query
          name: finishingId
          required: false
          type: string
          allowEmptyValue: false
          description: Returns the finishing for the id
        - in: query
          name: width
          required: true
          type: number
          allowEmptyValue: false
          description: The width of the trimmed product in millimetres
        - in: query
          name: height
          required: true
          type: number
          allowEmptyValue: false
          description: The height of the trimmed product in millimetres
        - in: query
          name: paperWeight
          required: true
          type: number
          allowEmptyValue: false
          description: The weight of the paper in gsm
        - in: query
          name: printType
          required: false
          type: integer
          description: The type of printing (1=Offset, 2=Digital, 3=Offset OR Digital)
        - in: query
          name: book.pp
          required: false
          type: integer
          description: The number of printed pages in the book. NB if any book parameters are specified then all book parameters must be specified
        - in: query
          name: book.orientation
          required: false
          type: integer
          description: The orientation of the book(0=Portrait, 1=Landscape). NB if any book parameters are specified then all book parameters must be specified
      responses:
        200:
          description: Finishings Resource
          schema:
            type: object
        401:
          $ref: "#/responses/Unauthorized"
  /man/finishings/{id}:
    get: 
      operationId: getFinishingsById
      summary: Returns finishing
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the finishing
          type: string
      responses:
        200:
          description: Finishing Resource
        400:
          description: Invalid id
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /man/pricing/standard:
    post:
      operationId: getProductPrice
      summary: Creates a price for a standard product
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: wizard
          required: true
          description: The details of the product to price
          schema:
            type: object
            required:
              - productId
              - quantity
              - kinds
            properties:
              productId:
                type: string
                description: The id of the product to price
              finishedSize:
                $ref: "#/definitions/Size"
              quantity:
                type: integer
                description: The number of finished items of each kind
              kinds:
                type: integer
                description: The number of different kinds
              deliveryType:
                type: integer
                description: The type of delivery (0=To Reseller, 1=Pickup, 2=To Customer)
              printType:
                type: integer
                description: The type of printing (1=Offset, 2=Digital, 3=Offset OR Digital)
              finishing:
                type: array
                description: Finishing to apply to this product
                items:
                  type: object
                  properties:
                    finishingId:
                      type: string
                      description: The id of the finishing
                    noItems:
                      type: integer
                      description: The number of finished items to apply this finishing to
      responses:
        200:
          description: Product Price Resource
        400:
          description: Bad request, invalid product wizard
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /man/pricing/wideformat:
    post:
      operationId: getWideFormatPrice
      summary: Creates a price for a wide format product
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: wizard
          in: body
          required: true
          description: The details of the wide format product to price
          schema:
            type: object
            required:
              - productId
              - quantity
              - kinds
            properties:
              productId:
                type: string
                description: The id of the product to price
              finishedSize:
                $ref: "#/definitions/Size"
              quantity:
                type: integer
                description: The number of finished items of each kind
              kinds:
                type: integer
                description: The number of different kinds
              deliveryType:
                type: integer
                description: The type of delivery (0=To Reseller, 1=Pickup, 2=To Customer)
              finishing:
                type: array
                description: Finishing to apply to this product
                items:
                  type: object
                  properties:
                    finishingId:
                      type: string
                      description: The id of the finishing
                    config:
                      type: object
                      description: The configuration settings for the finishing. Keys relate to the configuration option
      responses:
        200:
          description: Wide Format Product Price Resource
        400:
          description: Bad request, invalid wide format product wizard
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /man/orders:
    get:
      operationId: getOrders
      summary: Returns orders
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: orderId
          required: false
          description: The id of the order to be returned
          type: string
        - in: query
          name: resellerId
          required: false
          description: The id of the reseller to be used to filter the orders
          type: string
        - in: query
          name: filterBy
          required: false
          description: The type of filter to be used on the orders collection
          type: string
        - in: query
          name: filter
          required: false
          description: The filter to be used on the orders collection
          type: string
        - in: query
          name: sort
          required: false
          description: The field which the orders will be sorted by. Default is DateOrderd
          type: string
        - in: query
          name: asc
          required: false
          description: The sort direction. Default is false
          type: boolean
        - in: query
          name: pg
          required: false
          description: The page size when returning paged results. Default is 20
          type: integer
        - in: query
          name: ix
          required: false
          description: The page index when returning paged results. Default is 0
          type: integer
      responses:
        200:
          description: Orders Resource
        401:
          $ref: "#/responses/Unauthorized"
    post:
      operationId: postOrder
      summary: Creates an order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: order
          required: true
          description: Order details
          schema:
            type: object
            required:
              - reference
              - quoteId
            properties:
              reference:
                type: string
                description: The resellers reference to this order
              quoteId:
                type: string
                description: The id of the quote to order (productId must not be specified)
      responses:
        200:
          description: Order Resource
        400:
          description: Bad request
        401:
          $ref: "#/responses/Unauthorized"
        409:
          description: When the quote has already been ordered
  /man/orders/{id}:
    get:
      operationId: getOrderById
      summary: Returns order
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the order
          type: string
      responses:
        200:
          description: Order Resource
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /man/orders/{id}/artwork:
    get:
      operationId: getOrderArtworkById
      summary: Returns artwork info for an order
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the order
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Order Artwork Resource
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
    post:
      operationId: postOrderArtwork
      summary: Upload artwork
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the order
          type: string
        - in: body
          name: artwork
          required: true
          description: Order details
          schema:
            type: object
            required:
              - filename
            properties:
              filename:
                type: string
                description: The name of the file to be uploaded
              md5:
                type: string
                description: The MD5 checksum for the file contents (This will be used by the server to validate the received contents)
      responses:
        200:
          description: Artwork Resource
        400:
          description: Bad request
        401:
          $ref: "#/responses/Unauthorized"
        409:
          description: When a file attached to this order already exists with the same name
host: api.cmykhub.com
securityDefinitions:
  API Key:
    type: apiKey
    name: api_key
    in: header
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
definitions:
  # Schema for error response body
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
  Size:
    type: object
    properties: 
      width:
        type: number
        description: The width in millimetres
      height:
        type: number
        description: The height in millimetres